language: rust
sudo: false
cache: cargo

rust:
  # first 2018 edition
  - 1.31.0
  - nightly

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose

before_deploy:
  - cargo doc --verbose
  - echo '<meta http-equiv="refresh" content="0; url=llvm_config/index.html" /> ' > target/doc/index.html
  - cp -r target/doc public

deploy:
  - provider: pages
    edge: true
    github_token: "$GITHUB_TOKEN"
    local_dir: public
    on:
      branch: master
      rust: nightly
